### ISSUE TITLE
Is there any instruction on how to run this code?

### ISSUE THREAD

**Issue by dbxmcf** [ThePhD/dd-rf-2d#1]
Dear Author,

I have cloned the entire repository and compiled it using VS 2015 on a windows 10, the compilation completed successfully, however is there any instructions on how to run an example?

I noticed there are 3 executables under the "Release" build: 

data_generation.exe
dd-rf-2d.exe
ranger.exe

I tried to run dd-rf-2d.exe however windows poped out an error saying "stopped working", could you please provide some instructions on how to run this code?

Thank you so much!

Roy

**Comment by ThePhD** [comment]
Unfortunately, there isn't. I never got to return tot his code and I got the chance to revisit this and get it to build properly outside of my hacked up environment. This code actually wasn't even supposed to say up here that long, so I'll probably be closing it out.

Good luck searching for something that actually works. I unfortunately don't know of any other open source attempts at 2d stochastic fluid modeling, asides from the PBF stuff NVidia's already released and addendums/blogposts on it.

Good luck.
